'use client'
import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import './globals.css'
import Navbar from './component/Navbar'
 import Head from 'next/head'
import Image from 'next/image'
import OpenMenu from "@/app/utility/images/OpenMenu.png";
import React, { useState } from 'react'
import dynamic from 'next/dynamic'
import Loading from './component/Loading'
 

	
const poppins = Poppins({
  	
    weight: ['200', '300','400','500','600','700'],
  
    subsets: ['latin'],
  	
    variable: '--font-Poppins',
  	
  });
const inter = Inter({ subsets: ['latin'] })

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const BottomBar = dynamic(()=>import('./component/Bottombar'),{
  ssr:false,
  loading: ()=> <>
  <Loading />
  </>
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
})
{

const [openMobileNav, setOpenMobileNav] = useState<Boolean>(false);


  return (
    <html lang="en">
      <Head>

      <link href="https://fonts.cdnfonts.com/css/routhem" rel="stylesheet" />

      </Head>
      
                
      <body className={poppins.className}>
        <Navbar openMobileNav={openMobileNav} setOpenMenu={setOpenMobileNav}/>
       {!openMobileNav && <Image 
        src={OpenMenu}
        width={100}
        height={100}
        alt='open'
        className='w-[40px] h-[30px] absolute right-[10%] top-[30px] z-[101] lg:hidden xl:hidden'
        onClick={()=>setOpenMobileNav(true)}
        loading='lazy'
        />}
        {children}
        <BottomBar />
         
       </body>

    </html>
  )
}
