import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import './globals.css'
import Navbar from './component/Navbar'
import Bottombar from './component/Bottombar'
import Head from 'next/head'

	
const poppins = Poppins({
  	
    weight: ['200', '300','400','500','600','700'],
  
    subsets: ['latin'],
  	
    variable: '--font-Poppins',
  	
  });
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>

      <link href="https://fonts.cdnfonts.com/css/routhem" rel="stylesheet" />

      </Head>
      
                
      <body className={poppins.className}>
        <Navbar />

        {children}
        <Bottombar />
      </body>

    </html>
  )
}
